### ISSUE TITLE
terminal vim-mode

### ISSUE THREAD

**Issue by yofriadi** [caenrique/nvim-toggle-terminal#3]
hi thanks for the plugin, but I notice if I put this code I can scroll around my terminal neovim
`tnoremap <expr> <Esc> (&filetype == "fzf") ? "<Esc>" : "<c-\><c-n>"`

however if I remove it I can use my terminal vim-mode like https://github.com/softmoth/zsh-vim-mode,
but I also want that ability to scroll my terminal around,
I am think for using double Esc to do the above code.

I almost got it right with this code but some weird that I don't understand,
it shows `execute:_` after the line
`tnoremap <silent><Esc> <Esc>:<c-\><c-n>`

I wish you could help, thankyou

**Comment by caenrique** [comment]
Hi, this map is for exiting terminal mode in neovim. I believe that's why you are experiencing those things:
- with the mapping, you exit terminal-mode and scroll the buffer like any other buffer
- without the mapping you are scrolling the terminal like any other terminal outside vim

you can have both. I suggest to read the manual on [termial-mode](http://neovim.io/doc/user/nvim_terminal_emulator.html) in neovim to know how it works
the mapping I suggested was to use this ability together with fzf, but if you just want the normal mapping, it would be something like:

```
tnoremap <Esc> <C-\><C-n>
```

**Comment by yofriadi** [comment]
thankyou sooo much, much better for me now
